
openapi: "3.0.0"
info:
  title: Saramin Job API
  version: "1.0.0"
servers:
  - url: "http://localhost:5000"
paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
      responses:
        201:
          description: User registered successfully

