
openapi: "3.0.0"
info:
  title: Saramin Job API
  version: "1.0.0"
servers:
  - url: "http://localhost:5000"
paths:
  /jobs:
    get:
      summary: "Get job postings"
      responses:
        "200":
          description: "A list of job postings"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
