const express = require('express');
const { swaggerUi, specs } = require('./swagger');
const authRoutes = require('./routes/auth');
const jobRoutes = require('./routes/jobs');
require('dotenv').config();
const PORT = process.env.PORT || 3000;
const app = express();
app.use(express.json());
app.use('/auth', authRoutes);
app.use('/jobs', jobRoutes);
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));
app.listen(PORT, () => console.log(`Server running on http://0.0.0.0:${PORT}`));